### ISSUE TITLE
can not work as plugin in Elasticsearch 1.5

### ISSUE THREAD

**Issue by lubaogui** [spinscale/elasticsearch-suggest-plugin#37]
at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
Caused by: java.lang.VerifyError: class de.spinscale.elasticsearch.rest.action.suggest.RestSuggestAction overrides final method handleRequest.(Lorg/elasticsearch/rest/RestRequest;Lorg/elasticsearch/rest/RestChannel;)V
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at de.spinscale.elasticsearch.plugin.suggest.SuggestPlugin.onModule(SuggestPlugin.java:55)

have any plan to deal with ES 1.5?

**Comment by spinscale** [comment]
This is true. I havent updated the plugin for quite some time. The completion suggester and especially its successor, that gets hopefully released with elasticsearch 2.0, should be able to cover all of the functionality.

Developing this plugin further does not make a lot of sense given the above facts.
